# Generated by Django 5.1.3 on 2024-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/'),
        ),
    ]
